### ISSUE TITLE
One problem with this tracking

### ISSUE THREAD

**Issue by TimDaub** [opensource-observer/oss-directory#135]
hey,

I like this tracking, but e.g. my project Kiwi News, we've deliberately created a p2p network like Farcaster to avoid having to use L2 storage so that it can be used in more high-security context like financial applications

<img width="766" alt="Screenshot 2023-11-10 at 10 00 02" src="https://github.com/opensource-observer/oss-directory/assets/2758453/c607c322-d382-45cb-94d1-83033dbda160">

Vitalik also thematized that in his most recent blog post. E.g. as of today our network stores 5500 signed EIP712 messages that we've prevented from being stored on L2s. Yet, the website suggests that impact is "most number of contract interactions" etc.

<img width="783" alt="Screenshot 2023-11-10 at 10 00 30" src="https://github.com/opensource-observer/oss-directory/assets/2758453/88319ba5-abc5-46d2-93ed-aa4494338f6d">

We had a lot of impact based on our numbers https://news.kiwistand.com/stats but they wouldn't show up in the charts on this website, which is a bummer.

**Comment by ryscheng** [comment]
I love that you guys have a public KPI dashboard!
I completely agree that getting other forms of user analytics is critical to this effort. We are starting with on-chain analytics because it's easy, but we absolutely want to get to indexing other forms of user analytics like you guys have. Holy grail would be able to tie in Google Analytics or equivalent for any kind of web app.

I'm curious what analytics tooling do you guys use? Let's file issues in the oso repo to track getting that to work

**Comment by ryscheng** [comment]
FWIW, User analytics is a primary focus for this upcoming quarter.

This milestone is probably the one to track
https://github.com/opensource-observer/oso/milestone/5

I really appreciate the feedback, we will look to your examples for inspiration as we try to do this for the universe of dApps on the OP Superchain!
