### ISSUE TITLE
Python library for `fetchData`

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oss-directory#18]
It'd be nice to also publish to pip something similar to what we did with the npm library here.
Just fetch the latest changes into dictionaries/lists that you can use in Python

See here for reference
https://github.com/opensource-observer/oss-directory/blob/main/src/fetchData.ts

**Comment by davidgasquez** [comment]
Curious if instead of generating a library for each language, you could package the data into a CSV (after each commit with GitHub actions) and publish it somewhere (GitHub, S3, IPFS, ...) so it is `curl`able / downloadable.

Then in Python, getting the data could be `pd.read_csv(oso.io/directory.csv)` or something like that.

**Comment by ryscheng** [comment]
Yes! That's a great idea. I'm curious if you have any suggestions for how to encode the nested project schema?
https://github.com/opensource-observer/oss-directory/blob/main/src/resources/schema/project.json

Would you just create the equivalent relational tables to flatten it?

**Comment by ryscheng** [comment]
https://pypi.org/project/oss-directory/
